#!/bin/bash

# RemasterCow, script for creating module from changes for DebianDog by Fred (fredx181)
 
[ "`whoami`" != "root" ] && exec gsu ${0}

devs="$(blkid -o list | grep /dev | grep -E -v "swap|ntfs|vfat" | sort | cut -d" " -f1 | grep -E -v "/loop|sr0|swap" | sed 's|/dev/||g')"
echo $devs
DEVS=`echo $devs | sed 's/ /!/g'`
SETUP=`yad --title="RemasterCow (create module from changes)" --center --text=" This script will create a module from the changes you made to the system.  \n Advised is to run this script from terminal to watch progress.  \n Choose where to create new module, must be on linux filesystem, \n  ntfs or fat filesytems are excluded." \
--window-icon="preferences-system" --form  \
--field="  Choose drive to create module on::CBE" "$DEVS" \
--field="Type custom name of working directory \n  (e.g. changed):" "" \
--field="Type name for module with extension \n(e.g. 02-changes.squashfs or 02-changes.xzm):" "" \
--button="gtk-quit:1" --button="gtk-ok:0"`
ret=$?
[[ $ret -eq 1 ]] && exit 0

DRV="`echo $SETUP | cut -d "|" -f 1`"
WRKDIR="`echo $SETUP | cut -d "|" -f 2`"
SFS="`echo $SETUP | cut -d "|" -f 3`"


if [ -z "$DRV" ] || [ -z "$WRKDIR" ] || [ -z "$SFS" ]; then
yad --title="RemasterCow (create module from changes)" --center --text=" You probably did not fill in all fields, \n Please run the script again" --button="gtk-close:0"
exit 0
fi
mkdir /mnt/$DRV 2> /dev/null
mount /dev/$DRV /mnt/$DRV 2> /dev/null
if [ -d "/mnt/$DRV/$WRKDIR" ]; then
yad --title="RemasterCow (create module from changes)" --center --text=" Directory "/mnt/$DRV/$WRKDIR" already exists, \n Please run the script again and use other name" --button="gtk-close:0"
exit 0
fi
mkdir -p "/mnt/$DRV/$WRKDIR" # Make new directory.

if [ -e "/mnt/$DRV/$SFS" ]; then
yad --title="RemasterCow (create module from changes)" --center --text=" File "/mnt/$DRV/$SFS" already exists, \n Please run the script again and use other name" --button="gtk-close:0"
exit 0
fi

running(){ ps $1 | grep $1 >/dev/null; }

TOTAL=$(du -cbs --apparent-size /live/cow/* | awk 'END {print $1}')

echo "Copying files to /mnt/$DRV/$WRKDIR..."

cp -a /live/cow/* "/mnt/$DRV/$WRKDIR" &
CPPID=$!

trap "kill $CPPID" 2 15

(
   while running $CPPID; do
    
      COPY=$(du -cbs --apparent-size "/mnt/$DRV/$WRKDIR"/* 2> /dev/null | awk 'END {print $1}')
       
      PERC=$((COPY*100/TOTAL))
      echo $PERC

   done   
   echo 100
   sleep 1    
) | yad --title="RemasterCow (create module from changes)" --center --height="100" --width="400" --progress --no-buttons --auto-close --text=" Copying files to "/mnt/$DRV/$WRKDIR"... "

#mkdir -p "/mnt/$DRV/$WRKDIR"/{dev,live,lib/live/mount,proc,run,mnt,media,sys,tmp}
#cp -a /dev/console "/mnt/$DRV/$WRKDIR"/dev
#chmod a=rwx,o+t "/mnt/$DRV/$WRKDIR"/tmp

echo "Cleaning..."
rm -rf "/mnt/$DRV/$WRKDIR"/{dev,tmp,mnt,media,run,lost+found}
rm -f "/mnt/$DRV/$WRKDIR"/var/lib/alsa/asound.state
rm -f "/mnt/$DRV/$WRKDIR"/root/.bash_history
rm -f "/mnt/$DRV/$WRKDIR"/root/.xsession-errors
rm -rf "/mnt/$DRV/$WRKDIR"/root/.cache
rm -rf "/mnt/$DRV/$WRKDIR"/root/.thumbnails
rm -f "/mnt/$DRV/$WRKDIR"/etc/blkid-cache
rm -f "/mnt/$DRV/$WRKDIR"/etc/resolv.conf
rm -rf "/mnt/$DRV/$WRKDIR"/etc/udev/rules.d/70-persistent*
rm -f "/mnt/$DRV/$WRKDIR"/var/lib/dhcp/dhclient.eth0.leases
rm -f "/mnt/$DRV/$WRKDIR"/var/lib/dhcpcd/*.lease
ls "/mnt/$DRV/$WRKDIR"/var/lib/apt/lists | grep -v "lock" | grep -v "partial" | xargs -i rm "/mnt/$DRV/$WRKDIR"/var/lib/apt/lists/{} ; 

ls "/mnt/$DRV/$WRKDIR"/var/cache/apt/archives | grep -v "lock" | grep -v "partial" | xargs -i rm "/mnt/$DRV/$WRKDIR"/var/cache/apt/archives/{} ;

ls "/mnt/$DRV/$WRKDIR"/var/cache/apt | grep -v "archives" | xargs -i rm "/mnt/$DRV/$WRKDIR"/var/cache/apt/{} ;
find "/mnt/$DRV/$WRKDIR" -maxdepth 1 -type l -delete
	
cd "/mnt/$DRV/$WRKDIR"

zerosize() {
  find $* | while read file; do
    echo -n "."
    rm -f $file
    touch $file
  done
}

    zerosize usr/share/doc -type f -size +1c
    zerosize usr/share/doc -type l

    zerosize usr/share/man -type f -size +1c
    zerosize usr/share/man -type l


    zerosize usr/share/info -type f -size +1c
    zerosize usr/share/info -type l
    chown -R man:root usr/share/man
    #rm -rf dev tmp mnt media run lost+found
 
    find . -name '.wh.*' -delete

yad --title="RemasterCow (create module from changes)" --center --text=" Now you may want to do some extra cleaning to save more space before creating module with mksquashfs.\n For example: ~/.mozilla  \n Open filemanager in '/mnt/$DRV/$WRKDIR' to do so. \n  When done click the 'CreateModule' button to finally create:\n   '/mnt/$DRV/$SFS'" --button="CreateModule:0" --button="Cancel:1" 
ret=$?
[[ $ret -eq 1 ]] && exit 0

cd /mnt/$DRV
echo "Creating module..."
xterm -T "RemasterCow (create module from changes)" -si -sb -fg white -bg SkyBlue4 -geometry 65x14 -e "mksquashfs "/mnt/$DRV/$WRKDIR" "$SFS" -comp xz -b 1M -Xbcj x86"
yad --title="RemasterCow (create module from changes)" --center --width="400" --text=" Done creating '/mnt/$DRV/$SFS' \n Do you want to remove '/mnt/$DRV/$WRKDIR'? " --button="gtk-yes:0" --button="gtk-no:1"
ret=$?
[[ $ret -eq 1 ]] && exit 0
if [ -d "/mnt/$DRV/$WRKDIR" ]; then
rm -rf "/mnt/$DRV/$WRKDIR"
fi
exit 0
